{"name": "test_credKart_Login_params_003[GetDataForLogin2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testCases.test_Login_params.Test_credKart_Login_params object at 0x00000219AE1DCA90>\nsetup = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"c3f281bc-8b0c-46d1-946a-a64efcde0f5f\")>\nGetDataForLogin = ('Credenceppb3@test1.com', 'Credence@123')\n\n    def test_credKart_Login_params_003(self,setup,GetDataForLogin):\n        self.driver = setup\n        self.driver.find_element(By.XPATH,\"//a[normalize-space()='Login']\").click()\n        self.driver.find_element(By.XPATH, \"//input[@id='email']\").send_keys(GetDataForLogin[0])\n        self.driver.find_element(By.XPATH, \"//input[@id='password']\").send_keys(GetDataForLogin[1])\n        self.driver.find_element(By.XPATH, \"//button[@type='submit']\").click()\n    \n        try:\n>           self.driver.find_element(By.XPATH,\"//h2[normalize-space()='CredKart']\")\n\ntestCases\\test_Login_params.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:741: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x00000219AE2523D0>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"Unable to locate element: //h2[normalize-spac.../content/shared/webdriver/Errors.sys.mjs:509:5\\\\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //h2[normalize-space()='CredKart']; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testCases.test_Login_params.Test_credKart_Login_params object at 0x00000219AE1DCA90>\nsetup = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"c3f281bc-8b0c-46d1-946a-a64efcde0f5f\")>\nGetDataForLogin = ('Credenceppb3@test1.com', 'Credence@123')\n\n    def test_credKart_Login_params_003(self,setup,GetDataForLogin):\n        self.driver = setup\n        self.driver.find_element(By.XPATH,\"//a[normalize-space()='Login']\").click()\n        self.driver.find_element(By.XPATH, \"//input[@id='email']\").send_keys(GetDataForLogin[0])\n        self.driver.find_element(By.XPATH, \"//input[@id='password']\").send_keys(GetDataForLogin[1])\n        self.driver.find_element(By.XPATH, \"//button[@type='submit']\").click()\n    \n        try:\n            self.driver.find_element(By.XPATH,\"//h2[normalize-space()='CredKart']\")\n            print(\"Login testcase is Passed\")\n            self.driver.save_screenshot(\".\\\\ScreenShots\\\\\"+GetDataForLogin[0]+\"_\"+GetDataForLogin[1]+\"_\"+\"test_credKart_Login_params_003_Passed.PNG\")\n            self.driver.close()\n            assert True\n        except:\n            print(\"Login testcase is Failed\")\n            self.driver.save_screenshot(\".\\\\ScreenShots\\\\\"+GetDataForLogin[0]+\"_\"+GetDataForLogin[1]+\"_\"+\"test_credKart_Login_params_003_Failed.PNG\")\n            self.driver.close()\n>           assert False\nE           assert False\n\ntestCases\\test_Login_params.py:37: AssertionError"}, "attachments": [{"name": "stdout", "source": "fcbe5504-060e-480b-ab22-cefe5e2334f4-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "GetDataForLogin", "value": "('Credenceppb3@test1.com', 'Credence@123')"}], "start": 1708629394977, "stop": 1708629398640, "uuid": "b8b2e31f-adfc-480c-9d2a-da78bb35d7eb", "historyId": "c398bddffc6cc41eda965e42004624d6", "testCaseId": "3aea96ccf85727936550205e32d227e6", "fullName": "testCases.test_Login_params.Test_credKart_Login_params#test_credKart_Login_params_003", "labels": [{"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_Login_params"}, {"name": "subSuite", "value": "Test_credKart_Login_params"}, {"name": "host", "value": "DESKTOP-OJCC0SH"}, {"name": "thread", "value": "7552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_Login_params"}]}